// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(ApptContext))]
    [Migration("20220324210937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleTours.Models.ApptModel", b =>
                {
                    b.Property<int>("ApptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfAppt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeOfAppt")
                        .HasColumnType("TEXT");

                    b.HasKey("ApptId");

                    b.ToTable("Appts");

                    b.HasData(
                        new
                        {
                            ApptId = 1,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 2,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 3,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 4,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 5,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 6,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 7,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 8,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 9,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 10,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 11,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 12,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 13,
                            Available = true,
                            DayOfAppt = "Sunday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 14,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 15,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 16,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 17,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 18,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 19,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 20,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 21,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 22,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 23,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 24,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 25,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 26,
                            Available = true,
                            DayOfAppt = "Monday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 27,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 28,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 29,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 30,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 31,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 32,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 33,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 34,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 35,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 36,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 37,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 38,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 39,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 40,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 41,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 42,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 43,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 44,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 45,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 46,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 47,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 48,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 49,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 50,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 51,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 52,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 53,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 54,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 55,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 56,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 57,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 58,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 59,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 60,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 61,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 62,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 63,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 64,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 65,
                            Available = true,
                            DayOfAppt = "Thursday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 66,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 67,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 68,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 69,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 70,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 71,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 72,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 73,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 74,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 75,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 76,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 77,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 78,
                            Available = true,
                            DayOfAppt = "Friday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            ApptId = 79,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            ApptId = 80,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            ApptId = 81,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            ApptId = 82,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            ApptId = 83,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            ApptId = 84,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            ApptId = 85,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            ApptId = 86,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            ApptId = 87,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            ApptId = 88,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            ApptId = 89,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            ApptId = 90,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            ApptId = 91,
                            Available = true,
                            DayOfAppt = "Saturday",
                            GroupSize = 0,
                            TimeOfAppt = "8:00PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
