// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TempleTours.Models;

namespace TempleTours.Migrations
{
    [DbContext(typeof(ApptContext))]
    partial class ApptContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("TempleTours.Models.ApptModel", b =>
                {
                    b.Property<int>("ApptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ApptId");

                    b.ToTable("Appts");
                });

            modelBuilder.Entity("TempleTours.Models.ApptTime", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Available")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayOfAppt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeOfAppt")
                        .HasColumnType("TEXT");

                    b.HasKey("TimeId");

                    b.ToTable("ApptTimes");

                    b.HasData(
                        new
                        {
                            TimeId = 1,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 2,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 3,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 4,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 5,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 6,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 7,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 8,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 9,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 10,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 11,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 12,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 13,
                            Available = true,
                            DayOfAppt = "Sunday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 14,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 15,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 16,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 17,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 18,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 19,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 20,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 21,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 22,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 23,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 24,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 25,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 26,
                            Available = true,
                            DayOfAppt = "Monday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 27,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 28,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 29,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 30,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 31,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 32,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 33,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 34,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 35,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 36,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 37,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 38,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 39,
                            Available = true,
                            DayOfAppt = "Tuesday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 40,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 41,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 42,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 43,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 44,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 45,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 46,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 47,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 48,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 49,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 50,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 51,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 52,
                            Available = true,
                            DayOfAppt = "Wednesday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 53,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 54,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 55,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 56,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 57,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 58,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 59,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 60,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 61,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 62,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 63,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 64,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 65,
                            Available = true,
                            DayOfAppt = "Thursday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 66,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 67,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 68,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 69,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 70,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 71,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 72,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 73,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 74,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 75,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 76,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 77,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 78,
                            Available = true,
                            DayOfAppt = "Friday",
                            TimeOfAppt = "8:00PM"
                        },
                        new
                        {
                            TimeId = 79,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "8:00AM"
                        },
                        new
                        {
                            TimeId = 80,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "9:00AM"
                        },
                        new
                        {
                            TimeId = 81,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "10:00AM"
                        },
                        new
                        {
                            TimeId = 82,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "11:00AM"
                        },
                        new
                        {
                            TimeId = 83,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "12:00PM"
                        },
                        new
                        {
                            TimeId = 84,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "1:00PM"
                        },
                        new
                        {
                            TimeId = 85,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "2:00PM"
                        },
                        new
                        {
                            TimeId = 86,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "3:00PM"
                        },
                        new
                        {
                            TimeId = 87,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "4:00PM"
                        },
                        new
                        {
                            TimeId = 88,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "5:00PM"
                        },
                        new
                        {
                            TimeId = 89,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "6:00PM"
                        },
                        new
                        {
                            TimeId = 90,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "7:00PM"
                        },
                        new
                        {
                            TimeId = 91,
                            Available = true,
                            DayOfAppt = "Saturday",
                            TimeOfAppt = "8:00PM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
